version: '3.8'

services:

  mysql:
    container_name: tp-nfp-107_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: null
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./scripts:/scripts

  phpmyadmin:
    container_name: tp-nfp-107_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 512M
    ports:
      - '8080:80'
    depends_on:
      - mysql